### ISSUE TITLE
How will I know if my code contributions will pass build/test?

### ISSUE THREAD

**Issue by mblomdahl** [Fijo-Lurk/LocationRecord#10]
When I contribute to GitHub projects, I often find they have some kind of Continuous Integration \[CI] in place to check that code contributions builds and pass all tests + style rules. I think it would be a great improvement if this project had the same CI tools enabled. On GitHub I often find that developers use [Travis CI](https://github.com/travis-ci/travis-ci) for lightweight use cases. Maybe it could be added here?

**Comment by Fijo-Lurk** [comment]
Travis Ci is not added and is working having some problem running karma test through travis 

Getting this error,
any thoughts on what's wrong in my .travis.yml file @mblomdahl 

`16 03 2022 15:30:44.911:INFO [karma-server]: Karma v6.3.17 server started at http://localhost:9876/
16 03 2022 15:30:44.911:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
16 03 2022 15:30:44.913:INFO [launcher]: Starting browser Chrome
16 03 2022 15:30:45.681:ERROR [launcher]: Cannot start Chrome
	
16 03 2022 15:30:45.694:ERROR [launcher]: Chrome stdout: 
16 03 2022 15:30:45.695:ERROR [launcher]: Chrome stderr: 
16 03 2022 15:30:45.704:INFO [launcher]: Trying to start Chrome again (1/2).
16 03 2022 15:30:46.078:ERROR [launcher]: Cannot start Chrome
	
16 03 2022 15:30:46.078:ERROR [launcher]: Chrome stdout: 
16 03 2022 15:30:46.078:ERROR [launcher]: Chrome stderr: 
16 03 2022 15:30:46.130:INFO [launcher]: Trying to start Chrome again (2/2).
16 03 2022 15:30:46.503:ERROR [launcher]: Cannot start Chrome
	
16 03 2022 15:30:46.503:ERROR [launcher]: Chrome stdout: 
16 03 2022 15:30:46.504:ERROR [launcher]: Chrome stderr: 
16 03 2022 15:30:46.527:ERROR [launcher]: Chrome failed 2 times (cannot start). Giving up.
✔ Browser application bundle generation complete.
16 03 2022 15:30:52.363:WARN [karma]: No captured browser, open http://localhost:9876/
✔ Browser application bundle generation complete.
16 03 2022 15:30:53.878:WARN [karma]: No captured browser, open http://localhost:9876/`
