### ISSUE TITLE
The "EditorConfig" File is Missing in Repo Root, but Present in `frontend/`

### ISSUE THREAD

**Issue by mblomdahl** [Fijo-Lurk/LocationRecord#12]
The `frontend/.editorconfig` should live in the repo root, where a project is typically opened in the IDE of choice. Now my editor will not pick up that it (presumably) applies to all the files under `server/` module as well.

**Comment by Fijo-Lurk** [comment]
editorconfig file is added in root

**Comment by Fijo-Lurk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [t](https://trello.com/c/tF64Pca4/35-t)
