### ISSUE TITLE
CORS Errors on API Calls

### ISSUE THREAD

**Issue by mblomdahl** [Fijo-Lurk/LocationRecord#23]
**Describe the bug**
When running the Angular app from the `ng serve` Angular dev server, API calls to the backend fail with "CORS" errors.

**To Reproduce**
1. Start Angular dev server
2. Open app on `http://localhost:4200`
3. Perform interaction that triggers a AJAX request to `http://localhost:3000/path/to/api/endpoint`
4. Open browser dev tools to see error in console

**Expected behavior**
API calls to the backend are not blocked by the browser.

**Screenshots**

<img width="514" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/786326/159021985-961a0fd3-c414-45a0-9b72-4cad5687db1c.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari

**Additional context**
What is CORS? https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by Fijo-Lurk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enable CORS for local development](https://trello.com/c/nU49xSgj/45-enable-cors-for-local-development)
