### ISSUE TITLE
Make all folders lowercase

### ISSUE THREAD

**Issue by akebrissman** [Fijo-Lurk/LocationRecord#3]
On the root level some folders starts with upper case letter "Server" and some with just lowercase "frontend".
Make all folders lowercase. 

![bild](https://user-images.githubusercontent.com/13290014/158011064-be34f383-6b46-41bc-80c1-0690dc474e71.png)

**Comment by Fijo-Lurk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make all folders lowercase](https://trello.com/c/D2hyjSg9/29-make-all-folders-lowercase)
