### ISSUE TITLE
Issue Templates Missing

### ISSUE THREAD

**Issue by mblomdahl** [Fijo-Lurk/LocationRecord#7]
I'm wondering how to contribute Issues in an orderly manner. Instead of writing about it here in a soon-forgotten issue discussion, maybe we could add [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) to the repo?

**Comment by Fijo-Lurk** [comment]
added default issue template

**Comment by Fijo-Lurk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [t](https://trello.com/c/oiaucxJm/37-t)
