### ISSUE TITLE
What branching strategy is used here?

### ISSUE THREAD

**Issue by mblomdahl** [Fijo-Lurk/LocationRecord#8]
An initial source of confusion when looking at this repo may be figuring out "which Git workflow is in use"? Only having a `develop` branch comes off as a bit unconventional. Maybe the repo could adopt [a named and standardized Git workflow](https://www.atlassian.com/git/tutorials/comparing-workflows)? Around here I often see GitHub Flow used, but there are other alternatives of course.

**Comment by Fijo-Lurk** [comment]
Grate point. i will read and implement your suggestion @mblomdahl

**Comment by Fijo-Lurk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [t](https://trello.com/c/jZyYOSQc/36-t)
